drop table if exists member CASCADE;
create table member
(
    // id -> bigint ( long ) + generated by default ... => Null 처리
    id bigint generated by default as identity,
    // varchar(255) -> 가변적 Character
    name varchar(255),
    // PK -> ID
primary key (id)
 );